//AUTH
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT_FAILED = "LOGOUT_FAILED";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

//SURVEYS
export const SURVEYS_LOAD_SUCCESS = "SURVEYS_LOAD_SUCCESS";
export const SURVEYS_LOAD_FAILED = "SURVEYS_LOAD_FAILED";